# Generated by Django 3.1.2 on 2020-11-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('age',), 'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
    ]
