# Generated by Django 3.1.2 on 2020-11-09 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerAsset',
            fields=[
                ('id', models.BigAutoField(help_text='主键id', primary_key=True, serialize=False)),
                ('sn', models.CharField(help_text='序列号', max_length=128, unique=True, verbose_name='序列号')),
                ('name', models.CharField(help_text='服务器名称', max_length=64, unique=True, verbose_name='服务器名称')),
                ('os_type', models.CharField(blank=True, choices=[('W', 'Windows'), ('A', 'Apple'), ('L', 'Linux')], default='W', help_text='操作系统名称', max_length=2, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, '在线'), (1, '下线'), (2, '未知'), (3, '故障'), (4, '备用')], default=0, verbose_name='设备状态')),
                ('manage_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='管理IP')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('flag_delted', models.BooleanField(default=False, null=True, verbose_name='删除标记')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator_id', to=settings.AUTH_USER_MODEL, verbose_name='记录者')),
                ('updator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updator_id', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '资产总表',
                'verbose_name_plural': '资产总表',
                'ordering': ('update_time',),
            },
        ),
    ]
