# Generated by Django 3.1.2 on 2020-11-12 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverasset',
            name='memo',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.CreateModel(
            name='DatabaseAsset',
            fields=[
                ('id', models.BigAutoField(help_text='主键id', primary_key=True, serialize=False)),
                ('db_type', models.CharField(choices=[('MSSQL', 'SQL Server'), ('Linux', 'Linux'), ('Oracle', 'Oracle')], max_length=8, verbose_name='数据库类型')),
                ('db_version', models.CharField(blank=True, max_length=128, null=True, verbose_name='数据库版本信息')),
                ('username', models.CharField(help_text='登录用户名', max_length=32, verbose_name='登录用户名')),
                ('password', models.CharField(help_text='登录密码', max_length=32, verbose_name='登录密码')),
                ('port', models.IntegerField(default='4433', verbose_name='数据库端口号')),
                ('memo', models.TextField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('flag_delted', models.BooleanField(default=False, null=True, verbose_name='删除标记')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='db_creator_id', to=settings.AUTH_USER_MODEL, verbose_name='记录者')),
                ('manage_ip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='server_id', to='cmdb.serverasset', verbose_name='所在服务器')),
                ('updator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='db_updator_id', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '数据库清单表',
                'verbose_name_plural': '数据库清单表',
                'ordering': ('update_time',),
            },
        ),
    ]
